version: '3.9'

services:
  java_app:
    container_name: manager-restaurant
    image: manager-restaurant
    restart: always
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=db-wrz2z
    networks:
      - spring-postgres
    depends_on:
      - db

  db:
    container_name: manager-restaurant-db
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: db-wrz2z
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-postgres

volumes:
  db-data:

networks:
  spring-postgres:
    driver: bridge