version: '3.9'

services:
  java_app:
    container_name: java_app
    image: derick/java_app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    networks:
      - spring-postgres
    depends_on:
      - db

  db:
    container_name: manager_restaurant
    image: postgres:latest
    restart: always
    secrets:
      - db-password
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-postgres

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt

networks:
  spring-postgres:
