name: Continuous Integration with Github Actions

on:
  push:
    branches: 
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3.0.0
      with:   
        username: derickccastro
        password: Tj.140220

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven

    - name: Build Application JAR
      working-directory: ./
      run: |
        pwd
        mvn clean package -DskipTests

    - name: Docker Compose Build
      working-directory: ./
      run: docker compose build

    - name: List Docker Images
      run: docker images

    - name: Push to Docker Hub Container Registry
      run: |
        docker tag derickccastro/manager-restaurant:latest derickccastro/manager-restaurant:${{github.run_id}}

        docker push derickccastro/manager-restaurant:${{github.run_id}}
        docker push derickccastro/manager-restaurant:latest
        

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    # - name: Update dependency graph
    #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
